### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by borkovacd** [borkovacd/UKS#19]
- [x] create milestone/problem

- [x] update milestone

- [x] delete milestone/label 

- [x] close/open problem

- [x] link/unlink milestone

**Comment by olgaSavic** [comment]
Finished testing

**Comment by olgaSavic** [comment]
- [ ] remove label from problem

- [ ] remove assignee from problem

- [ ] update comment

- [ ] delete comment

- [ ] remove collaborator

**Comment by olgaSavic** [comment]
Testing finished Part 2
